config/routes.rb
Rails.application.routes.draw do
  resources :histories
  resources :notes
  resources :medicals
  resources :events
  resources :meetings
  devise_for :users
  resources :patients
  resources :searches
  resources :logs

  resources :conversations do
    resources :messages
  end

  root 'home#index'
  get 'calendar' => 'calendar#index', as: 'calendar'
  get 'about' => 'about#index', as: 'about'
  get 'help' => 'help#index', as: 'help'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/history.rb
class History < ApplicationRecord
  belongs_to :patient
  has_many :events
end

app/models/medical.rb
class Medical < ApplicationRecord
  belongs_to :patient
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :patient
end

app/models/patient.rb
class Patient < ApplicationRecord

  belongs_to :user
  has_one :medical
  has_one :history
  has_many :notes

  has_attached_file :image, styles: { large: "600x600>", meduim: "300x300>", thumb: "150x150#"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  def self.search(search)
      if search
        where(["forename LIKE ?","%#{search}%"])
      else
        all
      end
  end
end

app/models/search.rb
class Search < ApplicationRecord

  def search_patients

    patient = Patient.all

    patient = patient.where(["forename ILIKE ?","%#{forename}%"]) if forename.present?
    patient = patient.where(["surname ILIKE ?","%#{surname}%"]) if surname.present?
    patient = patient.where(["town ILIKE ?","%#{town}%"]) if town.present?
    patient = patient.where(["sex ILIKE ?","%#{sex}%"]) if sex.present?
    patient = patient.where(["age ILIKE ?","%#{age}%"]) if age.present?
    patient = patient.where(["postcode ILIKE ?","%#{postcode}%"]) if postcode.present?

    return patient
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :patients

  acts_as_messageable

  def mailboxer_email(object)
    nil
  end

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/controllers/help_controller.rb
class HelpController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    @patients = Patient.all.where(:user_id => current_user.id)
    @events = Event.all.order("updated_at DESC").where(start_time: Date.today.beginning_of_day..Date.today.end_of_day)
    @medical = Medical.all
    @conversations = current_user.mailbox.conversations
  end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  def index
    @patients = Patient.all.order("updated_at DESC")
    @searches = Search.all.order("updated_at DESC")

  end

  # Use callbacks to share common setup or constraints between actions.
  def set_patient
    @patient = Patient.find(params[:id])
  end

  def set_search
    @search = Search.find(params[:id])
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def patient_params
    params.require(:patient).permit(:forename, :surname, :age, :postcode, :sex, :county, :address, :number, :contactmethod, :email, :town, :title, :image)
  end

  def search_params
    params.require(:search).permit(:forename, :surname, :sex, :town, :age, :image, :postcode)
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
    @patients = Patients.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:title, :body)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:forename, :surname, :age, :postcode, :sex, :county, :address, :number, :contactmethod, :email, :town, :title, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/medicals_helper.rb
module MedicalsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/notes/_form.html.erb
<%= form_with(model: note, local: true) do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-12">

      <div class="field">
        <%= form.label :title %>
        <%= form.text_field :title, id: :note_title, :class => "form-control" %>
      </div>

    </div>
    <div class="col-md-12">

      <div class="field">
        <%= form.label :body %>
        <%= form.text_area :body, id: :note_body, :class => "form-control", :rows => "7" %>
      </div>

      <br>

      <div class="actions">
        <%= form.submit :class => "btn btn-success pull-right" %>
      </div>
    </div>

    </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Editing Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.title %></td>
        <td><%= note.body %></td>
        <td><%= link_to 'Show', note %></td>
        <td><%= link_to 'Edit', edit_note_path(note) %></td>
        <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Note', new_note_path %>

app/views/notes/new.html.erb
<h1>New Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<div id="page-wrapper">

  <div class="container-fluid">

    <!-- Page Heading -->
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header">
          <%= @patient.forename %>
          <%= @patient.surname %>
          <small>Patient No.
            <%= @patient.id %>
          </small>
        </h1>
        <ol class="breadcrumb">
          <li class="active">
            <i class="fa fa-dashboard"></i>
            Home
          </li>
        </ol>
        <% if flash[:notice] %>
          <div class="alert alert-success alert-dismissable">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <%= flash[:notice] %></div>
        <% end %>
      </div>
    </div>
    <!-- /.row -->

    <div class="row">
      <div class="col-lg-3">
      <%= link_to 'Personal Information', patient_path(), class: "list-group-item text-center" %>
      </div>
      <div class="col-lg-3">
        <%= link_to 'Medical Records', medical_path(), class: "list-group-item text-center" %>
      </div>
      <div class="col-lg-3">
        <%= link_to 'Appiontment History', history_path(), class: "list-group-item  text-center" %>
      </div>
      <div class="col-lg-3">
          <%= link_to 'Notes', note_path(), class: "list-group-item active text-center" %>
      </div>
    </div>
    <!-- /.row -->


    <br />

    <div class="row">
      <div class="col-lg-6">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">
              <i class="fa fa-user fa-fw"></i>
              <%= @patient.forename %>
              <%= @patient.surname %></h3>
          </div>
          <div class="panel-body">

          <%= render 'form', note: @note %>

          </div>
        </div>
      </div>

      <div class="col-lg-6">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">
              <i class="fa fa-user fa-fw"></i>
              Note History</h3>
          </div>
          <div class="panel-body">

            <%= form_with(model: @note, local: true) do |form| %>

            <div class="field">
              <%= form.label :created_at %>
              <%= form.text_field :created_at, :id => "disabledTextInput", :class => "form-control" %>
            </div>

            <div class="field">
              <%= form.label :updated_at %>
              <%= form.text_field :updated_at, :class => "form-control" %>
            </div>

            <% end %>

          </div>
        </div>
      </div>

    </div>
    <!-- /.row -->

  </div>
  <!-- /#page-wrapper -->

</div>
<!-- /#wrapper -->