config/routes.rb
Rails.application.routes.draw do
  resources :histories
  resources :notes
  resources :medicals
  resources :events
  resources :meetings
  devise_for :users
  resources :patients
  resources :searches
  resources :logs

  resources :conversations do
    resources :messages
  end

  root 'home#index'
  get 'calendar' => 'calendar#index', as: 'calendar'
  get 'about' => 'about#index', as: 'about'
  get 'help' => 'help#index', as: 'help'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/history.rb
class History < ApplicationRecord
  belongs_to :patient
  has_many :events
end

app/models/medical.rb
class Medical < ApplicationRecord
  belongs_to :patient
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :patient
end

app/models/patient.rb
class Patient < ApplicationRecord

  belongs_to :user
  has_one :medical
  has_one :history
  has_many :notes

  has_attached_file :image, styles: { large: "600x600>", meduim: "300x300>", thumb: "150x150#"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  def self.search(search)
      if search
        where(["forename LIKE ?","%#{search}%"])
      else
        all
      end
  end
end

app/models/search.rb
class Search < ApplicationRecord

  def search_patients

    patient = Patient.all

    patient = patient.where(["forename ILIKE ?","%#{forename}%"]) if forename.present?
    patient = patient.where(["surname ILIKE ?","%#{surname}%"]) if surname.present?
    patient = patient.where(["town ILIKE ?","%#{town}%"]) if town.present?
    patient = patient.where(["sex ILIKE ?","%#{sex}%"]) if sex.present?
    patient = patient.where(["age ILIKE ?","%#{age}%"]) if age.present?
    patient = patient.where(["postcode ILIKE ?","%#{postcode}%"]) if postcode.present?

    return patient
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :patients

  acts_as_messageable

  def mailboxer_email(object)
    nil
  end

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @conversations = current_user.mailbox.conversations
  end

  def show
    @conversation = current_user.mailbox.conversations.find(params[:id])
    @conversations = current_user.mailbox.conversations
  end

  def new
    @recipients = User.all - [current_user]
  end

  def create
    recipient = User.find(params[:user_id])
    receipt   = current_user.send_message(recipient, params[:body], params[:subject])
    redirect_to conversation_path(receipt.conversation)
  end
end

app/controllers/help_controller.rb
class HelpController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    @patients = Patient.all.where(:user_id => current_user.id)
    @events = Event.all.order("updated_at DESC").where(start_time: Date.today.beginning_of_day..Date.today.end_of_day)
    @medical = Medical.all
    @conversations = current_user.mailbox.conversations
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/medicals_helper.rb
module MedicalsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/conversations/index.html.erb
<div id="page-wrapper">

  <div class="container-fluid">

    <!-- Page Heading -->
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header">
          Messages
          <small>Inbox</small>
          <%= link_to "New Message", new_conversation_path, :class => "btn btn-success pull-right" %>
        </h1>
        <ol class="breadcrumb">
          <li>
            <a href="/">Home</a>
          </li>
            <li class="active">Messages</li>
        </ol>
      </div>
    </div>
    <!-- /.row -->

    <div class="row">
      <div class="col-lg-12">
        <% @conversations.each do |conversation| %>
          <div class="list-group">
            <a href="/conversations/<%= conversation.id %>" class="list-group-item">
              <h4 class="list-group-item-heading"><%= conversation.subject %></h4>
              <p class="list-group-item-text"><%= conversation.created_at.to_date %></p>
              <p class="list-group-item-text"></p>
            </a>
          </div>
        <% end %>
      </a>
    </div>
  </div>
  <!-- /.row -->

app/views/conversations/new.html.erb
<div id="page-wrapper">

  <div class="container-fluid">

    <!-- Page Heading -->
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header">
          New
          <small>Conversation</small>
          <%= link_to "New Message", new_conversation_path, :class => "btn btn-success pull-right" %>
        </h1>
        <ol class="breadcrumb">
          <li>
            <a href="/">Home</a>
          </li>
            <li class="active">Messages</li>
        </ol>
      </div>
    </div>
    <!-- /.row -->

    <div class="row">
      <div class="col-lg-4">

        <%= form_tag conversations_path, method: :post do %>
        <div>
          <label for="usr">User:</label>
          <%= select_tag :user_id, options_from_collection_for_select(@recipients, :id, :email), :class => "form-control" %>
        </div>

        <div>
          <label for="usr">Subject:</label>
          <%= text_field_tag :subject, nil, placeholder: "Subject", :class => "form-control" %>
        </div>

        <div>
          <label for="usr">Message:</label>
          <%= text_area_tag :body, nil, placeholder: "Leave a comment", :class => "form-control", :rows => "8" %>
        </div>

        <%= submit_tag("Submit", :class => "btn btn-success" ) %>
        <% end %>
    </div>
  </div>
  <!-- /.row -->

app/views/conversations/show.html.erb
<div id="page-wrapper">

  <div class="container-fluid">

    <!-- Page Heading -->
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header">
          <%= @conversation.subject %>
          <small>:Subject</small>
        </h1>
        <ol class="breadcrumb">
          <li class="active">
            <i class="fa fa-dashboard"></i>
            Home
          </li>
        </ol>
      </div>
    </div>
    <!-- /.row -->

    <!-- Nested media object -->
    <% @conversation.receipts_for(current_user).each do |receipt| %>
      <div class="media">
        <div class="media-left">
          <img src="img_avatar2.png" class="media-object" style="width:45px">
        </div>
        <div class="media-body">
          <h4 class="media-heading"><%= receipt.message.sender.email %>
            <small>
              <i><%= receipt.message.created_at.to_date %></i>
            </small>
          </h4>
          <p><%= receipt.message.body %></p>

        </div>
      <% end %>
    </div>

    <%= form_tag conversation_messages_path(@conversation), method: :post do %>

    <div>
    <%= text_area_tag :body, :class => "form-control", :rows => "8" %>
    </div>
    <div>
    <%= submit_tag("Submit", :class => "btn btn-success" ) %>
    </div>

  <% end %>

</div>
</div>