config/routes.rb
Rails.application.routes.draw do
  resources :histories
  resources :notes
  resources :medicals
  resources :events
  resources :meetings
  devise_for :users
  resources :patients
  resources :searches
  resources :logs

  resources :conversations do
    resources :messages
  end

  root 'home#index'
  get 'calendar' => 'calendar#index', as: 'calendar'
  get 'about' => 'about#index', as: 'about'
  get 'help' => 'help#index', as: 'help'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/history.rb
class History < ApplicationRecord
  belongs_to :patient
  has_many :events
end

app/models/medical.rb
class Medical < ApplicationRecord
  belongs_to :patient
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :patient
end

app/models/patient.rb
class Patient < ApplicationRecord

  belongs_to :user
  has_one :medical
  has_one :history
  has_many :notes

  has_attached_file :image, styles: { large: "600x600>", meduim: "300x300>", thumb: "150x150#"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  def self.search(search)
      if search
        where(["forename LIKE ?","%#{search}%"])
      else
        all
      end
  end
end

app/models/search.rb
class Search < ApplicationRecord

  def search_patients

    patient = Patient.all

    patient = patient.where(["forename ILIKE ?","%#{forename}%"]) if forename.present?
    patient = patient.where(["surname ILIKE ?","%#{surname}%"]) if surname.present?
    patient = patient.where(["town ILIKE ?","%#{town}%"]) if town.present?
    patient = patient.where(["sex ILIKE ?","%#{sex}%"]) if sex.present?
    patient = patient.where(["age ILIKE ?","%#{age}%"]) if age.present?
    patient = patient.where(["postcode ILIKE ?","%#{postcode}%"]) if postcode.present?

    return patient
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :patients

  acts_as_messageable

  def mailboxer_email(object)
    nil
  end

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/controllers/help_controller.rb
class HelpController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  before_action :set_history, only: [:show]
  before_action :set_patient, only: [:show]

  # GET /histories
  # GET /histories.json
  def index
    @histories = History.all
  end

  # GET /histories/1
  # GET /histories/1.json
  def show
    @history_events = History.find(params[:id])
    @events =  Event.where(:patient => @history_events).order('created_at DESC')
    @patients = Patient.all
  end

  # GET /histories/new
  def new
    @history = History.new
  end

  # GET /histories/1/edit
  def edit
  end

  # POST /histories
  # POST /histories.json
  def create
    @history = History.new(history_params)

    respond_to do |format|
      if @history.save
        format.html { redirect_to @history, notice: 'History was successfully created.' }
        format.json { render :show, status: :created, location: @history }
      else
        format.html { render :new }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /histories/1
  # PATCH/PUT /histories/1.json
  def update
    respond_to do |format|
      if @history.update(history_params)
        format.html { redirect_to @history, notice: 'History was successfully updated.' }
        format.json { render :show, status: :ok, location: @history }
      else
        format.html { render :edit }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /histories/1
  # DELETE /histories/1.json
  def destroy
    @history.destroy
    respond_to do |format|
      format.html { redirect_to histories_url, notice: 'History was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_history
      @history = History.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def history_params
      params.fetch(:history, {})
    end

    def set_patient
      @patient = Patient.find(params[:id])
    end

    def patient_params
      params.require(:patient).permit(:forename, :surname)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    @patients = Patient.all.where(:user_id => current_user.id)
    @events = Event.all.order("updated_at DESC").where(start_time: Date.today.beginning_of_day..Date.today.end_of_day)
    @medical = Medical.all
    @conversations = current_user.mailbox.conversations
  end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  def index
    @patients = Patient.all.order("updated_at DESC")
    @searches = Search.all.order("updated_at DESC")

  end

  # Use callbacks to share common setup or constraints between actions.
  def set_patient
    @patient = Patient.find(params[:id])
  end

  def set_search
    @search = Search.find(params[:id])
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def patient_params
    params.require(:patient).permit(:forename, :surname, :age, :postcode, :sex, :county, :address, :number, :contactmethod, :email, :town, :title, :image)
  end

  def search_params
    params.require(:search).permit(:forename, :surname, :sex, :town, :age, :image, :postcode)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/medicals_helper.rb
module MedicalsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/histories/_form.html.erb
<%= form_with(model: history, local: true) do |form| %>
  <% if history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(history.errors.count, "error") %> prohibited this history from being saved:</h2>

      <ul>
      <% history.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/histories/edit.html.erb
<h1>Editing History</h1>

<%= render 'form', history: @history %>

<%= link_to 'Show', @history %> |
<%= link_to 'Back', histories_path %>

app/views/histories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Histories</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @histories.each do |history| %>
      <tr>
        <td><%= link_to 'Show', history %></td>
        <td><%= link_to 'Edit', edit_history_path(history) %></td>
        <td><%= link_to 'Destroy', history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New History', new_history_path %>

app/views/histories/new.html.erb
<h1>New History</h1>

<%= render 'form', history: @history %>

<%= link_to 'Back', histories_path %>

app/views/histories/show.html.erb
<div id="page-wrapper">

  <div class="container-fluid">

    <!-- Page Heading -->
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header">
          <%= @patient.forename %>
          <%= @patient.surname %>
          <small>Patient No.
            <%= @patient.id %>
          </small>
        </h1>
        <ol class="breadcrumb">
          <li class="active">
            <i class="fa fa-dashboard"></i>
            Home
          </li>
        </ol>
        <% if flash[:notice] %>
          <div class="alert alert-success alert-dismissable">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <%= flash[:notice] %></div>
        <% end %>
      </div>
    </div>
    <!-- /.row -->

    <div class="row">
      <div class="col-lg-3">
        <%= link_to 'Medical Records', patient_path(), class: "list-group-item text-center" %>
      </a>
    </div>
    <div class="col-lg-3">
      <%= link_to 'Medical Records', medical_path(), class: "list-group-item text-center" %>
    </div>
    <div class="col-lg-3">
      <%= link_to 'Appointment History', history_path(), class: "list-group-item active text-center" %>
    </div>
    <div class="col-lg-3">
      <%= link_to 'Notes', note_path(), class: "list-group-item text-center" %>
    </div>
  </div>
  <!-- /.row -->

  <br/>

  <% if@events.empty? %>

    <div class="alert alert-info alert-dismissible">
      <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
      <strong>Warning!</strong>
      No previous appointments found in records.
    </div>

  <% else %>

  <div class="row">
    <div class="col-lg-12">
      <% @events.order('created_at DESC').limit(9).each do |event| %>
        <div class="list-group">
          <a href="/events/<%= event.id %>" class="list-group-item">
            <h4 class="list-group-item-heading"><%= event.id %>. <%= event.title %></h4>
            <p class="list-group-item-text"><%= event.description.truncate(150) %></p>
            <p class="list-group-item-text"><%= event.end_time.to_date %></p>
          </a>
        </div>
      <% end %>
      <% end %>
    </a>
  </div>
</div>
<!-- /.row -->

</div>
<!-- /#page-wrapper -->

</div>
<!-- /#wrapper -->