config/routes.rb
Rails.application.routes.draw do
  resources :histories
  resources :notes
  resources :medicals
  resources :events
  resources :meetings
  devise_for :users
  resources :patients
  resources :searches
  resources :logs

  resources :conversations do
    resources :messages
  end

  root 'home#index'
  get 'calendar' => 'calendar#index', as: 'calendar'
  get 'about' => 'about#index', as: 'about'
  get 'help' => 'help#index', as: 'help'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/history.rb
class History < ApplicationRecord
  belongs_to :patient
  has_many :events
end

app/models/medical.rb
class Medical < ApplicationRecord
  belongs_to :patient
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :patient
end

app/models/patient.rb
class Patient < ApplicationRecord

  belongs_to :user
  has_one :medical
  has_one :history
  has_many :notes

  has_attached_file :image, styles: { large: "600x600>", meduim: "300x300>", thumb: "150x150#"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  def self.search(search)
      if search
        where(["forename LIKE ?","%#{search}%"])
      else
        all
      end
  end
end

app/models/search.rb
class Search < ApplicationRecord

  def search_patients

    patient = Patient.all

    patient = patient.where(["forename ILIKE ?","%#{forename}%"]) if forename.present?
    patient = patient.where(["surname ILIKE ?","%#{surname}%"]) if surname.present?
    patient = patient.where(["town ILIKE ?","%#{town}%"]) if town.present?
    patient = patient.where(["sex ILIKE ?","%#{sex}%"]) if sex.present?
    patient = patient.where(["age ILIKE ?","%#{age}%"]) if age.present?
    patient = patient.where(["postcode ILIKE ?","%#{postcode}%"]) if postcode.present?

    return patient
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :patients

  acts_as_messageable

  def mailboxer_email(object)
    nil
  end

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/controllers/help_controller.rb
class HelpController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    @patients = Patient.all.where(:user_id => current_user.id)
    @events = Event.all.order("updated_at DESC").where(start_time: Date.today.beginning_of_day..Date.today.end_of_day)
    @medical = Medical.all
    @conversations = current_user.mailbox.conversations
  end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  def index
    @patients = Patient.all.order("updated_at DESC")
    @searches = Search.all.order("updated_at DESC")

  end

  # Use callbacks to share common setup or constraints between actions.
  def set_patient
    @patient = Patient.find(params[:id])
  end

  def set_search
    @search = Search.find(params[:id])
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def patient_params
    params.require(:patient).permit(:forename, :surname, :age, :postcode, :sex, :county, :address, :number, :contactmethod, :email, :town, :title, :image)
  end

  def search_params
    params.require(:search).permit(:forename, :surname, :sex, :town, :age, :image, :postcode)
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def new
    @search = Search.new
  end

  def create
    @search = Search.create(search_params)
    redirect_to @search
  end

  def show
    @search = Search.find(params[:id])
  end

  def search_params
    @search = Search.new
  end

  private

  def search_params
    params.require(:search).permit(:forename, :surname, :sex, :town, :age, :image, :postcode)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/medicals_helper.rb
module MedicalsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/new.html.erb
<div id="page-wrapper">

  <div class="container-fluid">

    <!-- Page Heading -->
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header">
          Advanced
          <small>Search</small>
        </h1>
        <ol class="breadcrumb">
          <li>
            <a href="/">Home</a>
          </li>
            <li class="active">Advanced Search</li>
        </ol>
        <% if flash[:notice] %>
          <div class="alert alert-danger alert-dismissable">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <%= flash[:notice] %></div>
        <% end %>
      </div>
    </div>
    <!-- /.row -->

    <div class="row">
      <div class="col-lg-12">
        <div class="panel panel-green">
          <div class="panel-heading">
            <h3 class="panel-title">
              <i class="fa fa-search fa-1x"></i>
              Advanced Search</h3>
          </div>
          <%= form_for @search, html: {class: "pure-form"} do |s| %>
          <div class="panel-body">
            <div class="row">
              <div class="col-md-6">

                <%= s.label :forename %>
                <%= s.text_field :forename, :class => "form-control" %>

                <%= s.label :surname %>
                <%= s.text_field :surname, :class => "form-control" %>

                <%= s.label :town %>
                <%= s.text_field :town, :class => "form-control" %>

                <br>

                <button type="reset" class="btn btn-default pull-left">Clear Form</button>

              </div>

              <div class="col-md-6">

                <%= s.label :age %>
                <%= s.text_field :age, :class => "form-control" %>

                <%= s.label :sex %>
                <%= s.select :sex, [["", ""], ["Male", "Male"], ["Female", "Female"], ["Transgender", "Transgender"]], {}, {class: "form-control"} %>

                <%= s.label :Post_code %>
                <%= s.text_field :postcode, :class => "form-control" %>

                <br>

                <div class="actions">
                  <%= s.submit "Search", class: "btn btn-success pull-right" %>
                </div>

              <% end %>

            </div>

          </div>
        </div>
      </div>
    </div>
    <!-- /.row -->

  </div>
  <!-- /#page-wrapper -->

</div>

</div>
<!-- /#wrapper -->

app/views/searches/show.html.erb
<div id="page-wrapper">

  <div class="container-fluid">

    <!-- Page Heading -->
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header">
          Search
          <small>Records</small>
          <%= link_to "Refine Search", new_search_path, :class => "btn btn-success pull-right" %>
        </h1>
        <ol class="breadcrumb">
          <li class="active">
            <i class="fa fa-dashboard"></i>
            Search
          </li>
        </ol>
        <% if flash[:notice] %>
          <div class="alert alert-danger alert-dismissable">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <%= flash[:notice] %></div>
        <% end %>
      </div>
    </div>
    <!-- /.row -->

    <% if@search.search_patients.empty? %>

      <div class="alert alert-danger alert-dismissible">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong>Warning!</strong>
        No search records found containing the criteria you entered.
      </div>

      <input action="action" onclick="window.history.go(-1); return false;" class="btn btn-default" type="button" value="Back"/>

    <% else %>

      <div class="row">
        <div class="col-lg-12">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">
                <i class="fa fa-search fa-1x"></i>
                Search Results</h3>
            </div>
            <div class="panel-body">

              <div class="row">
                <% @search.search_patients.each do |c| %>
                  <div class="col-md-3">
                    <div class="thumbnail">
                      <!-- <%= image_tag c.image.url(:meduim), :class => 'img-circle', :style => 'width:100px;height:100px' %> -->
                      <div class="caption">
                        <h3><%= c.forename %>
                          <%= c.surname %></h3>
                        <p><%= c.age %></p>
                        <p>ID No.
                          <%= c.id %></p>
                        <p>
                          <%= link_to 'View', patient_path(c.id), class: "btn btn-primary" %>
                        </p>
                      </div>
                    </div>

                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <!-- /.row -->

    </div>
    <!-- /#page-wrapper -->

  </div>
  <!-- /#wrapper -->

</div>

<% end %>